import { describe, it, expect } from "bun:test";
import { buildPlan, SchemaPatcher } from "../src";
import { PatchAggregator } from "../src/formatting/PatchAggregator";
import type { JsonObject } from "../src/types";
import schema from "../schema/schema.json";

describe("PatchAggregator", () => {
  const originalDoc = {
    envVariables: {},
    environments: [
      {
        id: "production-VuyfCU",
        name: "Production",
        region: "eu-north-1",
        source: { pr: false, branch: "master", trigger: "push" },
        services: [
          {
            ci: { type: "codebuild" },
            id: "job-scheduler-gWLzaf",
            cpu: 1,
            gpu: 0,
            jobs: {
              test: {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo tart"],
              },
              "test-1": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-2": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-4": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-5": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-6": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-7": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-8": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-9": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-10": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-11": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-12": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-14": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
            },
            name: "Job scheduler",
            type: "scheduler",
            memory: 2,
            target: { type: "fargate" },
            logging: {
              envVariables: {},
              cloudwatchLogsEnabled: true,
              ecsLogsMetadataEnabled: false,
            },
            basePath: ".",
            buildType: "docker",
            envVariables: {},
            dockerContext: ".",
            dockerfilePath: "Dockerfile",
            cpuArchitecture: ["x86_64"],
            containerInsights: false,
            versionHistoryCount: 10,
            includeEnvVariablesInBuild: true,
            injectEnvVariablesInDockerfile: true,
          },
        ],
        envVariables: {},
      },
    ],
  };

  const newDoc = {
    envVariables: {},
    environments: [
      {
        id: "production-VuyfCU",
        name: "New Production",
        region: "eu-north-1",
        source: { pr: false, branch: "new-branch", trigger: "push" },
        services: [
          {
            ci: { type: "codebuild" },
            id: "job-scheduler-gWLzaf",
            cpu: 1,
            gpu: 0,
            jobs: {
              test: {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo tart"],
              },
              "test-2": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-4": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-5": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-6": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-7": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-8": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test", "echo test added"],
              },
              "test-9": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-10": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-11": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-12": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
              "test-14": {
                timeout: 480,
                schedule: "manual",
                timezone: "UTC",
                startCommand: ["echo test"],
              },
            },
            name: "Job scheduler",
            type: "scheduler",
            memory: 2,
            target: { type: "fargate" },
            logging: {
              envVariables: {},
              cloudwatchLogsEnabled: true,
              ecsLogsMetadataEnabled: false,
            },
            basePath: ".",
            buildType: "docker",
            envVariables: {},
            dockerContext: ".",
            dockerfilePath: "Dockerfile",
            cpuArchitecture: ["x86_64", "arm64"],
            containerInsights: false,
            versionHistoryCount: 10,
            includeEnvVariablesInBuild: true,
            injectEnvVariablesInDockerfile: true,
          },
        ],
        envVariables: {},
      },
    ],
  };

  const patcher = new SchemaPatcher({ plan: buildPlan(schema as any) });
  const patches = patcher.createPatch(originalDoc, newDoc);

  const result = new PatchAggregator(originalDoc, newDoc).aggregate(patches, {
    pathPrefix: "/environments/0/services",
    plan: buildPlan(schema as any),
  });

  it("should produce correct diffLines", () => {
    expect(result.parentDiff.diffLines.unifiedDiffLines).toMatchInlineSnapshot(`
      [
        {
          "content": "{",
          "key": "unchanged-1-1",
          "newLineNumber": 1,
          "oldLineNumber": 1,
          "type": "unchanged",
        },
        {
          "content": "  "envVariables": {},",
          "key": "unchanged-2-2",
          "newLineNumber": 2,
          "oldLineNumber": 2,
          "type": "unchanged",
        },
        {
          "content": "  "environments": [",
          "key": "unchanged-3-3",
          "newLineNumber": 3,
          "oldLineNumber": 3,
          "type": "unchanged",
        },
        {
          "content": "    {",
          "key": "unchanged-4-4",
          "newLineNumber": 4,
          "oldLineNumber": 4,
          "type": "unchanged",
        },
        {
          "content": "      "id": "production-VuyfCU",",
          "key": "unchanged-5-5",
          "newLineNumber": 5,
          "oldLineNumber": 5,
          "type": "unchanged",
        },
        {
          "content": "      "name": "Production",",
          "key": "removed-6",
          "oldLineNumber": 6,
          "type": "removed",
        },
        {
          "content": "      "name": "New Production",",
          "key": "added-6",
          "newLineNumber": 6,
          "type": "added",
        },
        {
          "content": "      "region": "eu-north-1",",
          "key": "unchanged-7-7",
          "newLineNumber": 7,
          "oldLineNumber": 7,
          "type": "unchanged",
        },
        {
          "content": "      "source": {",
          "key": "unchanged-8-8",
          "newLineNumber": 8,
          "oldLineNumber": 8,
          "type": "unchanged",
        },
        {
          "content": "        "pr": false,",
          "key": "unchanged-9-9",
          "newLineNumber": 9,
          "oldLineNumber": 9,
          "type": "unchanged",
        },
        {
          "content": "        "branch": "master",",
          "key": "removed-10",
          "oldLineNumber": 10,
          "type": "removed",
        },
        {
          "content": "        "branch": "new-branch",",
          "key": "added-10",
          "newLineNumber": 10,
          "type": "added",
        },
        {
          "content": "        "trigger": "push"",
          "key": "unchanged-11-11",
          "newLineNumber": 11,
          "oldLineNumber": 11,
          "type": "unchanged",
        },
        {
          "content": "      },",
          "key": "unchanged-12-12",
          "newLineNumber": 12,
          "oldLineNumber": 12,
          "type": "unchanged",
        },
        {
          "content": "      "envVariables": {}",
          "key": "unchanged-13-13",
          "newLineNumber": 13,
          "oldLineNumber": 13,
          "type": "unchanged",
        },
        {
          "content": "    }",
          "key": "unchanged-14-14",
          "newLineNumber": 14,
          "oldLineNumber": 14,
          "type": "unchanged",
        },
        {
          "content": "  ]",
          "key": "unchanged-15-15",
          "newLineNumber": 15,
          "oldLineNumber": 15,
          "type": "unchanged",
        },
        {
          "content": "}",
          "key": "unchanged-16-16",
          "newLineNumber": 16,
          "oldLineNumber": 16,
          "type": "unchanged",
        },
      ]
    `);
    expect(result.childDiffs.get("job-scheduler-gWLzaf")?.diffLines.unifiedDiffLines)
      .toMatchInlineSnapshot(`
        [
          {
            "content": "{",
            "key": "unchanged-1-1",
            "newLineNumber": 1,
            "oldLineNumber": 1,
            "type": "unchanged",
          },
          {
            "content": "  "ci": {",
            "key": "unchanged-2-2",
            "newLineNumber": 2,
            "oldLineNumber": 2,
            "type": "unchanged",
          },
          {
            "content": "    "type": "codebuild"",
            "key": "unchanged-3-3",
            "newLineNumber": 3,
            "oldLineNumber": 3,
            "type": "unchanged",
          },
          {
            "content": "  },",
            "key": "unchanged-4-4",
            "newLineNumber": 4,
            "oldLineNumber": 4,
            "type": "unchanged",
          },
          {
            "content": "  "id": "job-scheduler-gWLzaf",",
            "key": "unchanged-5-5",
            "newLineNumber": 5,
            "oldLineNumber": 5,
            "type": "unchanged",
          },
          {
            "content": "  "cpu": 1,",
            "key": "unchanged-6-6",
            "newLineNumber": 6,
            "oldLineNumber": 6,
            "type": "unchanged",
          },
          {
            "content": "  "gpu": 0,",
            "key": "unchanged-7-7",
            "newLineNumber": 7,
            "oldLineNumber": 7,
            "type": "unchanged",
          },
          {
            "content": "  "jobs": {",
            "key": "unchanged-8-8",
            "newLineNumber": 8,
            "oldLineNumber": 8,
            "type": "unchanged",
          },
          {
            "content": "    "test": {",
            "key": "unchanged-9-9",
            "newLineNumber": 9,
            "oldLineNumber": 9,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-10-10",
            "newLineNumber": 10,
            "oldLineNumber": 10,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-11-11",
            "newLineNumber": 11,
            "oldLineNumber": 11,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-12-12",
            "newLineNumber": 12,
            "oldLineNumber": 12,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-13-13",
            "newLineNumber": 13,
            "oldLineNumber": 13,
            "type": "unchanged",
          },
          {
            "content": "        "echo tart"",
            "key": "unchanged-14-14",
            "newLineNumber": 14,
            "oldLineNumber": 14,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-15-15",
            "newLineNumber": 15,
            "oldLineNumber": 15,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-16-16",
            "newLineNumber": 16,
            "oldLineNumber": 16,
            "type": "unchanged",
          },
          {
            "content": "    "test-1": {",
            "key": "removed-17",
            "oldLineNumber": 17,
            "type": "removed",
          },
          {
            "content": "      "timeout": 480,",
            "key": "removed-18",
            "oldLineNumber": 18,
            "type": "removed",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "removed-19",
            "oldLineNumber": 19,
            "type": "removed",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "removed-20",
            "oldLineNumber": 20,
            "type": "removed",
          },
          {
            "content": "      "startCommand": [",
            "key": "removed-21",
            "oldLineNumber": 21,
            "type": "removed",
          },
          {
            "content": "        "echo test"",
            "key": "removed-22",
            "oldLineNumber": 22,
            "type": "removed",
          },
          {
            "content": "      ]",
            "key": "removed-23",
            "oldLineNumber": 23,
            "type": "removed",
          },
          {
            "content": "    },",
            "key": "removed-24",
            "oldLineNumber": 24,
            "type": "removed",
          },
          {
            "content": "    "test-2": {",
            "key": "unchanged-25-17",
            "newLineNumber": 17,
            "oldLineNumber": 25,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-26-18",
            "newLineNumber": 18,
            "oldLineNumber": 26,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-27-19",
            "newLineNumber": 19,
            "oldLineNumber": 27,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-28-20",
            "newLineNumber": 20,
            "oldLineNumber": 28,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-29-21",
            "newLineNumber": 21,
            "oldLineNumber": 29,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-30-22",
            "newLineNumber": 22,
            "oldLineNumber": 30,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-31-23",
            "newLineNumber": 23,
            "oldLineNumber": 31,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-32-24",
            "newLineNumber": 24,
            "oldLineNumber": 32,
            "type": "unchanged",
          },
          {
            "content": "    "test-4": {",
            "key": "unchanged-33-25",
            "newLineNumber": 25,
            "oldLineNumber": 33,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-34-26",
            "newLineNumber": 26,
            "oldLineNumber": 34,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-35-27",
            "newLineNumber": 27,
            "oldLineNumber": 35,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-36-28",
            "newLineNumber": 28,
            "oldLineNumber": 36,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-37-29",
            "newLineNumber": 29,
            "oldLineNumber": 37,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-38-30",
            "newLineNumber": 30,
            "oldLineNumber": 38,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-39-31",
            "newLineNumber": 31,
            "oldLineNumber": 39,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-40-32",
            "newLineNumber": 32,
            "oldLineNumber": 40,
            "type": "unchanged",
          },
          {
            "content": "    "test-5": {",
            "key": "unchanged-41-33",
            "newLineNumber": 33,
            "oldLineNumber": 41,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-42-34",
            "newLineNumber": 34,
            "oldLineNumber": 42,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-43-35",
            "newLineNumber": 35,
            "oldLineNumber": 43,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-44-36",
            "newLineNumber": 36,
            "oldLineNumber": 44,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-45-37",
            "newLineNumber": 37,
            "oldLineNumber": 45,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-46-38",
            "newLineNumber": 38,
            "oldLineNumber": 46,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-47-39",
            "newLineNumber": 39,
            "oldLineNumber": 47,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-48-40",
            "newLineNumber": 40,
            "oldLineNumber": 48,
            "type": "unchanged",
          },
          {
            "content": "    "test-6": {",
            "key": "unchanged-49-41",
            "newLineNumber": 41,
            "oldLineNumber": 49,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-50-42",
            "newLineNumber": 42,
            "oldLineNumber": 50,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-51-43",
            "newLineNumber": 43,
            "oldLineNumber": 51,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-52-44",
            "newLineNumber": 44,
            "oldLineNumber": 52,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-53-45",
            "newLineNumber": 45,
            "oldLineNumber": 53,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-54-46",
            "newLineNumber": 46,
            "oldLineNumber": 54,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-55-47",
            "newLineNumber": 47,
            "oldLineNumber": 55,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-56-48",
            "newLineNumber": 48,
            "oldLineNumber": 56,
            "type": "unchanged",
          },
          {
            "content": "    "test-7": {",
            "key": "unchanged-57-49",
            "newLineNumber": 49,
            "oldLineNumber": 57,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-58-50",
            "newLineNumber": 50,
            "oldLineNumber": 58,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-59-51",
            "newLineNumber": 51,
            "oldLineNumber": 59,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-60-52",
            "newLineNumber": 52,
            "oldLineNumber": 60,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-61-53",
            "newLineNumber": 53,
            "oldLineNumber": 61,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-62-54",
            "newLineNumber": 54,
            "oldLineNumber": 62,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-63-55",
            "newLineNumber": 55,
            "oldLineNumber": 63,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-64-56",
            "newLineNumber": 56,
            "oldLineNumber": 64,
            "type": "unchanged",
          },
          {
            "content": "    "test-8": {",
            "key": "unchanged-65-57",
            "newLineNumber": 57,
            "oldLineNumber": 65,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-66-58",
            "newLineNumber": 58,
            "oldLineNumber": 66,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-67-59",
            "newLineNumber": 59,
            "oldLineNumber": 67,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-68-60",
            "newLineNumber": 60,
            "oldLineNumber": 68,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-69-61",
            "newLineNumber": 61,
            "oldLineNumber": 69,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-70-62",
            "newLineNumber": 62,
            "oldLineNumber": 70,
            "type": "unchanged",
          },
          {
            "content": "        "echo test added"",
            "key": "added-63",
            "newLineNumber": 63,
            "type": "added",
          },
          {
            "content": "      ]",
            "key": "unchanged-71-64",
            "newLineNumber": 64,
            "oldLineNumber": 71,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-72-65",
            "newLineNumber": 65,
            "oldLineNumber": 72,
            "type": "unchanged",
          },
          {
            "content": "    "test-9": {",
            "key": "unchanged-73-66",
            "newLineNumber": 66,
            "oldLineNumber": 73,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-74-67",
            "newLineNumber": 67,
            "oldLineNumber": 74,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-75-68",
            "newLineNumber": 68,
            "oldLineNumber": 75,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-76-69",
            "newLineNumber": 69,
            "oldLineNumber": 76,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-77-70",
            "newLineNumber": 70,
            "oldLineNumber": 77,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-78-71",
            "newLineNumber": 71,
            "oldLineNumber": 78,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-79-72",
            "newLineNumber": 72,
            "oldLineNumber": 79,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-80-73",
            "newLineNumber": 73,
            "oldLineNumber": 80,
            "type": "unchanged",
          },
          {
            "content": "    "test-10": {",
            "key": "unchanged-81-74",
            "newLineNumber": 74,
            "oldLineNumber": 81,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-82-75",
            "newLineNumber": 75,
            "oldLineNumber": 82,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-83-76",
            "newLineNumber": 76,
            "oldLineNumber": 83,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-84-77",
            "newLineNumber": 77,
            "oldLineNumber": 84,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-85-78",
            "newLineNumber": 78,
            "oldLineNumber": 85,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-86-79",
            "newLineNumber": 79,
            "oldLineNumber": 86,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-87-80",
            "newLineNumber": 80,
            "oldLineNumber": 87,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-88-81",
            "newLineNumber": 81,
            "oldLineNumber": 88,
            "type": "unchanged",
          },
          {
            "content": "    "test-11": {",
            "key": "unchanged-89-82",
            "newLineNumber": 82,
            "oldLineNumber": 89,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-90-83",
            "newLineNumber": 83,
            "oldLineNumber": 90,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-91-84",
            "newLineNumber": 84,
            "oldLineNumber": 91,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-92-85",
            "newLineNumber": 85,
            "oldLineNumber": 92,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-93-86",
            "newLineNumber": 86,
            "oldLineNumber": 93,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-94-87",
            "newLineNumber": 87,
            "oldLineNumber": 94,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-95-88",
            "newLineNumber": 88,
            "oldLineNumber": 95,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-96-89",
            "newLineNumber": 89,
            "oldLineNumber": 96,
            "type": "unchanged",
          },
          {
            "content": "    "test-12": {",
            "key": "unchanged-97-90",
            "newLineNumber": 90,
            "oldLineNumber": 97,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-98-91",
            "newLineNumber": 91,
            "oldLineNumber": 98,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-99-92",
            "newLineNumber": 92,
            "oldLineNumber": 99,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-100-93",
            "newLineNumber": 93,
            "oldLineNumber": 100,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-101-94",
            "newLineNumber": 94,
            "oldLineNumber": 101,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-102-95",
            "newLineNumber": 95,
            "oldLineNumber": 102,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-103-96",
            "newLineNumber": 96,
            "oldLineNumber": 103,
            "type": "unchanged",
          },
          {
            "content": "    },",
            "key": "unchanged-104-97",
            "newLineNumber": 97,
            "oldLineNumber": 104,
            "type": "unchanged",
          },
          {
            "content": "    "test-14": {",
            "key": "unchanged-105-98",
            "newLineNumber": 98,
            "oldLineNumber": 105,
            "type": "unchanged",
          },
          {
            "content": "      "timeout": 480,",
            "key": "unchanged-106-99",
            "newLineNumber": 99,
            "oldLineNumber": 106,
            "type": "unchanged",
          },
          {
            "content": "      "schedule": "manual",",
            "key": "unchanged-107-100",
            "newLineNumber": 100,
            "oldLineNumber": 107,
            "type": "unchanged",
          },
          {
            "content": "      "timezone": "UTC",",
            "key": "unchanged-108-101",
            "newLineNumber": 101,
            "oldLineNumber": 108,
            "type": "unchanged",
          },
          {
            "content": "      "startCommand": [",
            "key": "unchanged-109-102",
            "newLineNumber": 102,
            "oldLineNumber": 109,
            "type": "unchanged",
          },
          {
            "content": "        "echo test"",
            "key": "unchanged-110-103",
            "newLineNumber": 103,
            "oldLineNumber": 110,
            "type": "unchanged",
          },
          {
            "content": "      ]",
            "key": "unchanged-111-104",
            "newLineNumber": 104,
            "oldLineNumber": 111,
            "type": "unchanged",
          },
          {
            "content": "    }",
            "key": "unchanged-112-105",
            "newLineNumber": 105,
            "oldLineNumber": 112,
            "type": "unchanged",
          },
          {
            "content": "  },",
            "key": "unchanged-113-106",
            "newLineNumber": 106,
            "oldLineNumber": 113,
            "type": "unchanged",
          },
          {
            "content": "  "name": "Job scheduler",",
            "key": "unchanged-114-107",
            "newLineNumber": 107,
            "oldLineNumber": 114,
            "type": "unchanged",
          },
          {
            "content": "  "type": "scheduler",",
            "key": "unchanged-115-108",
            "newLineNumber": 108,
            "oldLineNumber": 115,
            "type": "unchanged",
          },
          {
            "content": "  "memory": 2,",
            "key": "unchanged-116-109",
            "newLineNumber": 109,
            "oldLineNumber": 116,
            "type": "unchanged",
          },
          {
            "content": "  "target": {",
            "key": "unchanged-117-110",
            "newLineNumber": 110,
            "oldLineNumber": 117,
            "type": "unchanged",
          },
          {
            "content": "    "type": "fargate"",
            "key": "unchanged-118-111",
            "newLineNumber": 111,
            "oldLineNumber": 118,
            "type": "unchanged",
          },
          {
            "content": "  },",
            "key": "unchanged-119-112",
            "newLineNumber": 112,
            "oldLineNumber": 119,
            "type": "unchanged",
          },
          {
            "content": "  "logging": {",
            "key": "unchanged-120-113",
            "newLineNumber": 113,
            "oldLineNumber": 120,
            "type": "unchanged",
          },
          {
            "content": "    "envVariables": {},",
            "key": "unchanged-121-114",
            "newLineNumber": 114,
            "oldLineNumber": 121,
            "type": "unchanged",
          },
          {
            "content": "    "cloudwatchLogsEnabled": true,",
            "key": "unchanged-122-115",
            "newLineNumber": 115,
            "oldLineNumber": 122,
            "type": "unchanged",
          },
          {
            "content": "    "ecsLogsMetadataEnabled": false",
            "key": "unchanged-123-116",
            "newLineNumber": 116,
            "oldLineNumber": 123,
            "type": "unchanged",
          },
          {
            "content": "  },",
            "key": "unchanged-124-117",
            "newLineNumber": 117,
            "oldLineNumber": 124,
            "type": "unchanged",
          },
          {
            "content": "  "basePath": ".",",
            "key": "unchanged-125-118",
            "newLineNumber": 118,
            "oldLineNumber": 125,
            "type": "unchanged",
          },
          {
            "content": "  "buildType": "docker",",
            "key": "unchanged-126-119",
            "newLineNumber": 119,
            "oldLineNumber": 126,
            "type": "unchanged",
          },
          {
            "content": "  "envVariables": {},",
            "key": "unchanged-127-120",
            "newLineNumber": 120,
            "oldLineNumber": 127,
            "type": "unchanged",
          },
          {
            "content": "  "dockerContext": ".",",
            "key": "unchanged-128-121",
            "newLineNumber": 121,
            "oldLineNumber": 128,
            "type": "unchanged",
          },
          {
            "content": "  "dockerfilePath": "Dockerfile",",
            "key": "unchanged-129-122",
            "newLineNumber": 122,
            "oldLineNumber": 129,
            "type": "unchanged",
          },
          {
            "content": "  "cpuArchitecture": [",
            "key": "unchanged-130-123",
            "newLineNumber": 123,
            "oldLineNumber": 130,
            "type": "unchanged",
          },
          {
            "content": "    "x86_64"",
            "key": "unchanged-131-124",
            "newLineNumber": 124,
            "oldLineNumber": 131,
            "type": "unchanged",
          },
          {
            "content": "  ],",
            "key": "unchanged-132-125",
            "newLineNumber": 125,
            "oldLineNumber": 132,
            "type": "unchanged",
          },
          {
            "content": "  "containerInsights": false,",
            "key": "unchanged-133-126",
            "newLineNumber": 126,
            "oldLineNumber": 133,
            "type": "unchanged",
          },
          {
            "content": "  "versionHistoryCount": 10,",
            "key": "unchanged-134-127",
            "newLineNumber": 127,
            "oldLineNumber": 134,
            "type": "unchanged",
          },
          {
            "content": "  "includeEnvVariablesInBuild": true,",
            "key": "unchanged-135-128",
            "newLineNumber": 128,
            "oldLineNumber": 135,
            "type": "unchanged",
          },
          {
            "content": "  "injectEnvVariablesInDockerfile": true",
            "key": "unchanged-136-129",
            "newLineNumber": 129,
            "oldLineNumber": 136,
            "type": "unchanged",
          },
          {
            "content": "}",
            "key": "unchanged-137-130",
            "newLineNumber": 130,
            "oldLineNumber": 137,
            "type": "unchanged",
          },
          {
            "content": "}",
            "key": "stuck-j-131",
            "newLineNumber": 131,
            "type": "unchanged",
          },
        ]
      `)
  });

  it("should separate parent and child patches correctly", () => {
    expect(result.parentDiff.patches.length).toBe(2);
    expect(result.parentDiff.patches[0]?.path).toBe("/environments/0/name");
    expect(result.childDiffs.size).toBe(1);
  });

  it("should produce correct diff lines for children", () => {
    const service1Diff = result.childDiffs.get("job-scheduler-gWLzaf");
    expect(service1Diff?.addCount).toBe(1);
    expect(service1Diff?.removeCount).toBe(8);
  });

  it("should strip the child array from the parent diff", () => {
    const originalParent = result.parentDiff.original as JsonObject;
    const env = (originalParent.environments as JsonObject[])?.[0];
    expect(env?.services).toBeUndefined();

    const newParent = result.parentDiff.new as JsonObject;
    const newEnv = (newParent.environments as JsonObject[])?.[0];
    expect(newEnv?.services).toBeUndefined();
  });
});
