package schemapatch

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// differential_test.go replays the seeded differential-fuzz corpus generated by
// spec/fuzz/generate-corpus.ts. Each record pairs a (schema, options, original,
// modified) triple with the TypeScript reference's answer:
//
//	tsPatch   — ops from JsonSchemaPatcher.execute()
//	tsApplied — applyPatch(original, tsPatch) result
//
// For every record this test:
//  1. builds the same plan from the referenced schema + options,
//  2. diffs original→modified with the same capability toggles,
//  3. asserts its patch is STRUCTURALLY EQUAL to tsPatch (§10.3.2), and
//  4. applies ITS OWN patch to original and asserts the result deep-equals
//     tsApplied (§8.7.4) — and that apply never mutated the input.
//
// Zero mismatches are required. A divergence is a bug in the Go port, a bug in
// the TS reference, or a spec hole — investigate, do not paper over.
//
// The corpus lives at ../spec/fuzz/corpus relative to go/. When it is absent
// (the published-module case, where spec/ is not shipped) the whole test skips.

type fuzzRecord struct {
	Name      string          `json:"name"`
	SchemaRef string          `json:"schemaRef"`
	Options   fuzzOptions     `json:"options"`
	Original  json.RawMessage `json:"original"`
	Modified  json.RawMessage `json:"modified"`
	TSPatch   json.RawMessage `json:"tsPatch"`
	TSApplied json.RawMessage `json:"tsApplied"`
}

type fuzzOptions struct {
	PrimaryKeyMap            map[string]string `json:"primaryKeyMap"`
	BasePath                 string            `json:"basePath"`
	PrimaryKeyCandidates     []string          `json:"primaryKeyCandidates"`
	IncludeOldValue          bool              `json:"includeOldValue"`
	EmitMoves                bool              `json:"emitMoves"`
	WholesaleReplaceFallback bool              `json:"wholesaleReplaceFallback"`
}

func TestDifferentialFuzzCorpus(t *testing.T) {
	corpusDir := filepath.Join("..", "spec", "fuzz", "corpus")
	entries, err := os.ReadDir(corpusDir)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("fuzz corpus absent (published-module case)")
		}
		t.Fatalf("read corpus dir: %v", err)
	}

	// Cache the referenced schema files (decoded once through the order-preserving
	// value model, exactly as BuildPlan consumes them).
	schemaCache := make(map[string]Value)
	loadSchema := func(ref string) (Value, error) {
		if v, ok := schemaCache[ref]; ok {
			return v, nil
		}
		data, err := os.ReadFile(filepath.Join(corpusDir, "schemas", ref+".json"))
		if err != nil {
			return nil, err
		}
		v, err := Decode(data)
		if err != nil {
			return nil, err
		}
		schemaCache[ref] = v
		return v, nil
	}

	total := 0
	files := 0
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".jsonl" {
			continue
		}
		files++
		data, err := os.ReadFile(filepath.Join(corpusDir, entry.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		for lineNo, line := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
			if strings.TrimSpace(line) == "" {
				continue
			}
			var rec fuzzRecord
			if err := json.Unmarshal([]byte(line), &rec); err != nil {
				t.Fatalf("%s:%d parse record: %v", entry.Name(), lineNo+1, err)
			}
			total++
			t.Run(entry.Name()+"/"+rec.Name, func(t *testing.T) {
				runFuzzRecord(t, &rec, loadSchema)
			})
		}
	}
	if files == 0 || total == 0 {
		t.Fatal("no fuzz corpus records found")
	}
	t.Logf("differential fuzz records executed: %d across %d files", total, files)
}

func runFuzzRecord(t *testing.T, rec *fuzzRecord, loadSchema func(string) (Value, error)) {
	t.Helper()

	schema, err := loadSchema(rec.SchemaRef)
	if err != nil {
		t.Fatalf("load schema %q: %v", rec.SchemaRef, err)
	}
	plan, err := BuildPlan(schema, BuildPlanOptions{
		PrimaryKeyMap:        rec.Options.PrimaryKeyMap,
		BasePath:             rec.Options.BasePath,
		PrimaryKeyCandidates: rec.Options.PrimaryKeyCandidates,
	})
	if err != nil {
		t.Fatalf("BuildPlan: %v", err)
	}

	original, err := Decode(rec.Original)
	if err != nil {
		t.Fatalf("decode original: %v", err)
	}
	modified, err := Decode(rec.Modified)
	if err != nil {
		t.Fatalf("decode modified: %v", err)
	}

	patcher := NewPatcher(plan,
		IncludeOldValue(rec.Options.IncludeOldValue),
		EmitMoves(rec.Options.EmitMoves),
		WholesaleReplaceFallback(rec.Options.WholesaleReplaceFallback),
	)
	got := patcher.Execute(original, modified)

	// (1) Structural op equality against the TS reference patch (§10.3.2).
	want := decodeExpectedPatch(t, rec.TSPatch)
	assertOpsEqual(t, got, want)
	if t.Failed() {
		return
	}

	// (2) Apply the Go patch to a snapshot of original; the input must not
	// mutate, and the result must deep-equal the reference's tsApplied (§8.7.4).
	before := Clone(original)
	applied, err := ApplyPatch(original, got, ApplyOptions{})
	if err != nil {
		t.Fatalf("ApplyPatch failed: %v\npatch: %s", err, dumpOps(got))
	}
	if !DeepEqual(original, before) {
		t.Errorf("apply mutated the input document")
	}
	tsApplied, err := Decode(rec.TSApplied)
	if err != nil {
		t.Fatalf("decode tsApplied: %v", err)
	}
	if !DeepEqual(applied, tsApplied) {
		t.Errorf("applied result differs from tsApplied\n go: %s\nwant: %s",
			mustEncode(t, applied), mustEncode(t, tsApplied))
	}
}
